"""baseline schema: users, flask_dance_oauth, extra_sentence_groups

Revision ID: f7d207e6604f
Revises: 
Create Date: 2026-05-13 14:42:10.205713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7d207e6604f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='kagit'
    )
    op.create_table('extra_sentence_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_title', sa.String(length=200), nullable=False),
    sa.Column('sentences', sa.JSON(), nullable=False),
    sa.Column('localized_titles', sa.JSON(), nullable=True),
    sa.Column('localized_artists', sa.JSON(), nullable=True),
    sa.Column('card_image', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['kagit.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kagit'
    )
    op.create_table('flask_dance_oauth',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('browser_session_key', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['kagit.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'browser_session_key', 'provider', name='uq_user_browser_session_key_provider'),
    schema='kagit'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_dance_oauth', schema='kagit')
    op.drop_table('extra_sentence_groups', schema='kagit')
    op.drop_table('users', schema='kagit')
    # ### end Alembic commands ###
